// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkMCROL8XXWLke9wBuz-FR8PPleHOQK8c',
    appId: '1:1057089330672:web:6948fa4ab9914de0231135',
    messagingSenderId: '1057089330672',
    projectId: 'fire-danger-rating-notifier',
    authDomain: 'fire-danger-rating-notifier.firebaseapp.com',
    storageBucket: 'fire-danger-rating-notifier.appspot.com',
    measurementId: 'G-9JSCLLRZ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRj3VQlRtvDTYoph5ZI5Xiuz2cCqHerg',
    appId: '1:1057089330672:android:80afff490b05b28e231135',
    messagingSenderId: '1057089330672',
    projectId: 'fire-danger-rating-notifier',
    storageBucket: 'fire-danger-rating-notifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZv3O36MnPy31O7HV6hi0He1WwrAzN_Dc',
    appId: '1:1057089330672:ios:d3141864cbaf93cd231135',
    messagingSenderId: '1057089330672',
    projectId: 'fire-danger-rating-notifier',
    storageBucket: 'fire-danger-rating-notifier.appspot.com',
    iosBundleId: 'com.example.bushfireWarningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZv3O36MnPy31O7HV6hi0He1WwrAzN_Dc',
    appId: '1:1057089330672:ios:d3141864cbaf93cd231135',
    messagingSenderId: '1057089330672',
    projectId: 'fire-danger-rating-notifier',
    storageBucket: 'fire-danger-rating-notifier.appspot.com',
    iosBundleId: 'com.example.bushfireWarningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkMCROL8XXWLke9wBuz-FR8PPleHOQK8c',
    appId: '1:1057089330672:web:74cd86a735dbacce231135',
    messagingSenderId: '1057089330672',
    projectId: 'fire-danger-rating-notifier',
    authDomain: 'fire-danger-rating-notifier.firebaseapp.com',
    storageBucket: 'fire-danger-rating-notifier.appspot.com',
    measurementId: 'G-9NYJR61WNK',
  );
}
